### ISSUE TITLE
integration tests

### ISSUE THREAD

**Issue by filmaj** [architect/cli#7]
need to exercise the combination of using `package` and `deploy` and verifying infra on AWS exists as desired.

# TODO

- [ ] need an AWS account / creds to run against
- [ ] need to write test run `arc` package + deploy steps
- [ ] how to verify things on aws exist as desired? use `aws-sdk`?
